project:
  type: website
  output-dir: docs   # ensures GitHub Pages will work

website:
  title: "NEIL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: 1_infection.qmd
        text: "1 Infection"
    logo: images/babyphono_logo_purple.png
    
format:
  html:
    pretty_urls: true
    include-in-header: meta.html
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
