--- PAGE 1 ---
10
Tetralogy of Fallot
Tetralogy of Fallot is one of the more common cyanotic heart defects. Although
it had been described much earlier, it was Etienne-Louis Arthur Fallot who, in 1888,
separated this malformation from other anatomical lesions responsible for the ‘maladie
bleu’. The characteristic malformation is composed of four constant features
(Fig. 10.1), namely subpulmonary arterial stenosis, a ventricular septal defect, biven-
tricular origin of the aortic valve and hypertrophy of the right ventricle. The precise
anatomy can range from hearts with minimal aortic overriding and minimal pul-
monary stenosis to the extreme, where the pulmonary obstruction is so severe as to
represent the commonest form of pulmonary atresia with ventricular septal defect.
Morphological Hallmarks
In order to understand the morphology of the ventricular outlets in tetralogy
of Fallot, the muscular components must be carefully deﬁned. In normal hearts, a
prominent fold of muscle separates the leaﬂets of the tricuspid from those of the pul-
monary valves. This is the supraventricular crest (‘crista supraventricularis’). Anatom-
ically, it is mostly made up of the musculature of the inner heart curvature, which
we call the ventriculo-infundibular fold separating the subpulmonary and subaor-
tic outlets. In the normal heart, only a very small part of the supraventricular crest
can justiﬁably be described as an outlet septum. This is because the leaﬂets of the
pulmonary valve are supported by a sleeve of infundibular muscle that stands proud
of the ventricular mass (Fig. 10.2). Another important muscular structure within
the normal right ventricle, is the characteristic large trabeculation on the septum
(Fig. 10.3). This structure, the septomarginal trabeculation, is made up of a body
120


--- PAGE 2 ---
Tetralogy of Fallot
121
Figure 10.1 A specimen displayed in a fashion similar to the subcostal or right anterior
oblique view. The outlet septum (∗∗) has been transected to show the overriding of the
aortic valve through the ventricular septal defect and muscular subpulmonary stenosis in
Fallot’s tetralogy.
Figure 10.2 The right ventricular outﬂow tract is displayed in this normal heart. The
ventriculo-infundibular fold is clasped between the anterior (A) and posterior (P) limbs of
the septomarginal trabeculation. Smaller bundles of muscle, septo-parietal trabeculations (∗),
line the outﬂow.


--- PAGE 3 ---
122
Echocardiography in Congenital Heart Disease Made Simple
Figure 10.3 Schematic representation of the normal right ventricular outﬂow tract with
naming of the muscular structures.
that divides superiorly into anterior and posterior limbs. In the normal heart, the
supraventricular crest inserts into the ventricular septum between the limbs of the
septomarginal trabeculation.
In hearts with Fallot’s tetralogy, the normal architecture of the right ventricular
outlet is distorted with the various muscular components achieving identity as dis-
crete structures (Figs. 10.1 and 10.4). The outlet septum becomes a clearly deﬁned
right ventricular structure. It is inserted antero-cephalad to the anterior limb of the
septomarginal trabeculation. In this location, it creates muscular obstruction of the
subpulmonary outlet. Indeed, this antero-cephalad deviation of the outlet septum is
the hallmark for diagnosis. Other smaller trabeculations, also present in the normal
heart, contribute to the subpulmonary stenosis. These septoparietal trabeculations
encircle the parietal wall of the subpulmonary infundibulum, extending from the
anterior margin of the septomarginal trabeculation. They are prominent and hyper-
trophied in tetralogy (Fig. 10.5).
Because of its deviation into the right ventricular outﬂow tract, the outlet septum
is malaligned relative to the rest of the muscular septum. This is a general feature of
ventricular septal defects opening into the right ventricular outlet, with or without
tetralogy of Fallot. The malalignment means that the aortic valve overrides the


--- PAGE 4 ---
Tetralogy of Fallot
123
Figure 10.4 Schematic representation of the right ventricular outﬂow tract in Fallot’s tetral-
ogy. Note the insertion of the outlet septum to the anterior limb of the septomarginal
trabeculation.
ventricular septum, being attached in part to right ventricular structures (Fig. 10.6).
The outlet septum, therefore, is an exclusively right ventricular structure (Fig. 10.7).
Amongst hearts with these morphological hallmarks, there are variations in the
anatomy of the ventricular septal defect, the nature of pulmonary infundibular steno-
sis, the degree of aortic override and the associated malformations.
The Ventricular Septal Defect
This is nearly always large and non-restrictive, except in rare cases where it is
occluded by the leaﬂets of the tricuspid valve or tissue derived from them. When
viewed from the right ventricle, the typical defect is cradled between the limbs of
the septomarginal trabeculation and roofed by the leaﬂets of the overriding aortic
valve. Its anterior border is formed by the fusion of the deviated outlet septum with
the anterior limb of the septomarginal trabeculation (Fig. 10.8). The right ventricular
margin of the roof is formed by the ventriculo-infundibular fold supporting the
leaﬂets of the aortic valve.


--- PAGE 5 ---
124
Echocardiography in Congenital Heart Disease Made Simple
Figure 10.5 This heart with Fallot’s tetralogy shows hypertrophy of septoparietal trabec-
ulations (∗) exacerbating subpulmonary stenosis. The aortic valve is visible through the
perimembranous ventricular septal defect (arrow).
Figure 10.6 This right ventricular view shows the antero-cephalad deviation of the outlet
septum (∗∗) that causes narrowing of the subpulmonary outlet (). The aortic valve (open
arrow) has attachments to both ventricles.


--- PAGE 6 ---
Tetralogy of Fallot
125
Figure 10.7 (a) Subcostal right anterior oblique view of a normal heart. (b) Subcostal right
oblique section of Fallot’s tetralogy showing aortic override and antero-cephalad insertion
of the outlet septum (OS). (c) Colour ﬂow Doppler emphasised infundibular pulmonary
stenosis.
*
Aorta
Aorta
Tricuspid valve
Tricuspid valve
*
Pulm
trunk
Pulm
trunk
a
Ao
RV
LV
LA
Ao
Ao
PT
PT
RA
RA
TV
TV
RV
RV
RPA
RPA
LPA
LPA
OS
OS
b
c
*
Aorta
Aorta
Tricuspid valve
Tricuspid valve
*
Pulm
trunk
Pulm
trunk
a
Ao
RV
LV
LA
Ao
Ao
PT
PT
RA
RA
TV
TV
RV
RV
RPA
RPA
LPA
LPA
OS
OS
b
c
Ao
RV
LV
LA
Ao
Ao
PT
PT
RA
RA
TV
TV
RV
RV
RPA
RPA
LPA
LPA
OS
OS
b
c
Figure 10.8 (a) This magniﬁed view of Fig. 10.6 shows the borders of the ventricular septal
defect. This defect is described as a perimembranous defect owing to ﬁbrous continuity
between tricuspid, aortic and mitral valves at its postero-inferior border (between arrows).
The outlet septum (∗∗) is conﬁned to the right ventricle. (b) Parasternal long axis view shows
overriding of the aorta. (c) Parasternal short axis view shows a perimembranous ventricular
septal defect with tricuspid-aortic continuity, and anterior deviation of the outlet septum
producing infundibular stenosis.
The area showing most variability is found postero-inferiorly. In about four-ﬁfths
of cases, this margin is made up of ﬁbrous continuity between the leaﬂets of the aortic,
mitral and tricuspid valves (Fig. 10.8). In these cases, the defect is perimembranous,
and the atrioventricular conduction tissue penetrates through the area of ﬁbrous
continuity in the same way as in ‘isolated’ ventricular septal defects. The ﬁbrous
margin is duplicated in many of these cases to produce a so-called membranous ﬂap.
In the remaining ﬁfth of cases, there is muscular separation between the aortic and
tricuspid valves in the postero-inferior margin. This is produced by fusion of the


--- PAGE 7 ---
126
Echocardiography in Congenital Heart Disease Made Simple
Figure 10.9 The borders of the ventricular septal defect in this heart are completely muscu-
lar. There is override of the aortic valve but owing to fusion of the ventriculo-infundibular
fold to the posterior limb () of the septomarginal trabeculation the aortic valve is separated
from the tricuspid valve.
ventriculo-infundibular fold with the posterior limb of the septomarginal trabecula-
tion (Fig. 10.9). This muscle separating the leaﬂets of the aortic and tricuspid valves
in the right ventricular margin of the defect also serves to protect the atrioventricular
conduction tissues.
Some patients have hearts with an anatomical arrangement very similar to tetral-
ogy, but the ventricular septal defect is both subaortic and subpulmonary because of
complete absence of the muscular outlet septum. This anatomical variant is partic-
ularly frequent in patients from the Far East and South America. In these cases, the
ventricular septal defect is doubly committed and juxta-arterial. Many include these
cases in the diagnostic category of the tetralogy of Fallot.
Pulmonary Infundibular Stenosis
There is general agreement that pulmonary stenosis, in the form of narrowing of
the infundibulum, is an integral part of tetralogy. The major part of the obstruction is


--- PAGE 8 ---
Tetralogy of Fallot
127
Figure 10.10 The subpulmonary infundibulum (arrows) is elongated in this heart.
∗= outlet septum.
due to deviation of the outlet septum. While occasional hearts exhibit a hypoplastic
outlet septum, and, hence, a short subpulmonary infundibulum, most hearts have an
extensive infundibulum that is longer than normal (Fig. 10.10). The proximal extent
of the subpulmonary infundibulum is an oriﬁce, the so-called ‘os’ to the infundibu-
lum, which is surrounded by muscle. Further narrowing in this region is often due
to superimposed accretions of ﬁbrous tissue, and sometimes by hypertrophy of the
anterior limb of the septomarginal trabeculation. Additional, but more proximal,
stenosis may be caused by hypertrophy of the apical portion of the septomarginal
trabeculation. This apical obstruction produces one variant of the so-called ‘two
chambered right ventricle’, which can also exist without the infundibular morphol-
ogy of tetralogy of Fallot. Additional obstruction is usually present at the level of the
pulmonary valve. This is due either to fusion and doming of the valvar leaﬂets or
stenosis of a valve with two or three leaﬂets.
Overriding of the Aorta
Biventricular connection of the aortic valve usually described as overriding, is
an essential feature of tetralogy. There is, nonetheless, a marked variation in the
degree of rightward deviation of the aorta. The degree of override can be minimal,
with the aorta mostly connected to the left ventricle, in other words, with con-
cordant ventriculo-arterial connections. In other hearts, in contrast, the aortic valve
is attached almost entirely within the right ventricle, thus producing double outlet
ventriculo-arterial connection.


--- PAGE 9 ---
128
Echocardiography in Congenital Heart Disease Made Simple
Associated Malformations
An interatrial communication is a frequent additional ﬁnding. Additional ven-
tricular septal defects can also occur. If a second muscular inlet ventricular septal
defect is present, the conduction axis is in the muscle bar between the two defects.
Alternatively, the subaortic defect may extend inferiorly to the crux, producing an
extensive perimembranous defect though which the tricuspid valve may straddle and
override. The essence of this lesion is malalignment between the atrial and ventricu-
lar septal structures and, because of this, the conduction axis will be grossly abnormal.
In other hearts, there may be a common atrioventricular, valve with the subaortic
defect conﬂuent with the ventricular component of an atrioventricular septal defect.
Other important associations are non-conﬂuent origin of the pulmonary arteries,
stenosis of the pulmonary arteries themselves, variations in branching from the aortic
arch and origin of the anterior interventricular artery from the right coronary artery
(Fig. 10.11). A right aortic arch, while not of functional signiﬁcance, is present in
about a ﬁfth of cases with tetralogy. The arterial duct may be patent, closed or absent.
Absence of the duct is usually associated with another notable lesion, namely the
so-called ‘absence’ of the leaﬂets of the pulmonary valve (Fig. 10.12). In reality, these
usually form an annular array at the ventriculo-pulmonary junction, as rudimentary
Figure 10.11 (a) Short axis section demonstrating origin of the anterior interventricular
coronary artery (LAD) in the normal heart. (b) This case of Fallot’s tetralogy has the ori-
gin of the anterior interventricular coronary artery (LAD) from the right coronary artery
(RCA). The anterior interventricular artery courses along the anterior wall of the pulmonary
infundibulum.


--- PAGE 10 ---
Tetralogy of Fallot
129
Figure 10.12 (a) This heart with Fallot’s tetralogy is associated with under-development
of the pulmonary valve. Instead of semilunar leaﬂets, the valve is represented by a ridge.
(b) Subcostal right oblique section shows dilation of the right pulmonary artery in absent
pulmonary valve syndrome. Dysplastic rudiments of the pulmonary and hypoplastic outlet
septum are visible. There is a muscular postero-inferior rim to the ventricular septal defect,
which separates the tricuspid and aortic valves.
leaﬂets, but the major feature is the marked dilation of the pulmonary trunk and
arteries.
A very important subset of hearts with tetralogy have pulmonary atresia rather
than pulmonary stenosis. These are part of the spectrum of pulmonary atresia with
ventricular septal defect. They are of sufﬁcient clinical import to warrant separate
coverage.

